import { Router } from 'express';
import { requireAuth } from '../middlewares/authMiddleware.js';
import * as product from '../controllers/productV2Controller.js';

const router = Router();
router.use(requireAuth);
router.get('/users/me', product.getMe);
router.patch('/users/me', product.updateMe);
router.get('/users/:userId', product.getUser);
router.put('/users/:userId/follow', product.setFollow);
router.delete('/users/:userId/follow', product.removeFollow);
router.get('/users/:userId/followers', product.listFollowers);
router.get('/users/:userId/following', product.listFollowing);
router.get('/users/:userId/likes-given', product.listLikesGiven);
router.get('/onboarding/status', product.onboardingStatus);
router.put('/onboarding', product.completeOnboarding);
router.get('/repositories', product.listRepositories);
router.get('/repositories/trending', product.listTrending);
router.get('/repositories/saved', product.listSaved);
router.get('/repositories/:repoId', product.getRepository);
router.get('/repositories/:repoId/comments', product.listComments);
router.post('/repositories/:repoId/comments', product.createComment);
router.patch('/comments/:commentId', product.updateComment);
router.delete('/comments/:commentId', product.deleteComment);
router.get('/collections', product.listCollections);
router.post('/collections', product.createCollection);
router.put('/collections/:collectionId', product.updateCollection);
router.delete('/collections/:collectionId', product.deleteCollection);
router.get('/boards', product.listBoards);
router.post('/boards', product.createBoard);
router.put('/boards/:boardId', product.updateBoard);
router.delete('/boards/:boardId', product.deleteBoard);
router.get('/boards/:boardId/repositories', product.listBoardRepos);
router.put('/boards/:boardId/repositories/:repoId', product.addBoardRepo);
router.delete('/boards/:boardId/repositories/:repoId', product.removeBoardRepo);
export default router;
